name: Update README with recent activity graph

on:
   workflow_dispatch:

jobs:
  update-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Generate last 3 months parameter
        run: |
          END_DATE=$(date +%Y-%m-%d)
          START_DATE=$(date -d "$END_DATE -3 months" +%Y-%m-%d)
          echo "CUSTOM_TIME=${START_DATE}_to_${END_DATE}" >> $GITHUB_ENV
        
      - name: Update README
        run: |
          sed -i "s/custom_time=[^)]*/custom_time=$CUSTOM_TIME/" README.md
          
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update activity graph"
          git push
